services:
 facefusion-cuda:
  build:
   context: .
   dockerfile: Dockerfile
  command: [ 'uvicorn', 'faceapi:app', '--reload', '--host', '0.0.0.0', '--port', '8080' ]
  volumes:
  - .assets:/facefusion/.assets
  ports:
  - 8080:8080
  deploy:
   resources:
    reservations:
     devices:
     - driver: nvidia
       capabilities: [ gpu, video ]